# Imports

In [1]:
import pandas
from pandas import DataFrame        
from IPython.display import Markdown, display

# Dataset instanciation

## Raw instanciation

In [2]:
dataset: DataFrame = pandas.read_csv("data/caso_full.csv")

# These are all the information needed about the dataset

In [3]:
display(Markdown(f"**Amount of tuples**: {len(dataset)}"))

display(Markdown(f"**Column names and its types**:"))

columns_names_with_type: DataFrame = DataFrame(
    {
        "column_name": dataset.columns,
        "type": dataset.dtypes.values
    }    
)

columns_names_with_type

**Amount of tuples**: 3853648

**Column names and its types**:

                                      column_name     type
0                                            city   object
1                                  city_ibge_code  float64
2                                            date   object
3                            epidemiological_week    int64
4                            estimated_population  float64
5                       estimated_population_2019  float64
6                                         is_last     bool
7                                     is_repeated     bool
8                        last_available_confirmed    int64
9   last_available_confirmed_per_100k_inhabitants  float64
10                            last_available_date   object
11                      last_available_death_rate  float64
12                          last_available_deaths    int64
13                                order_for_place    int64
14                                     place_type   object
15                                          state   object
16                                  new_confirmed    int64
17                                     new_deaths    int64

### Sample of dataset

In [4]:
dataset.head(10)

,city,city_ibge_code,date,epidemiological_week,estimated_population,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
0,Rio Branco,1200401.0,2020-03-17,202012,413418.0,407319.0,False,False,3,0.72566,2020-03-17,0.0,0,1,city,AC,3,0
1,NaN,12.0,2020-03-17,202012,894470.0,881935.0,False,False,3,0.33539,2020-03-17,0.0,0,1,state,AC,3,0
2,Rio Branco,1200401.0,2020-03-18,202012,413418.0,407319.0,False,False,3,0.72566,2020-03-18,0.0,0,2,city,AC,0,0
3,NaN,12.0,2020-03-18,202012,894470.0,881935.0,False,False,3,0.33539,2020-03-18,0.0,0,2,state,AC,0,0
4,Rio Branco,1200401.0,2020-03-19,202012,413418.0,407319.0,False,False,4,0.96754,2020-03-19,0.0,0,3,city,AC,1,0
5,NaN,12.0,2020-03-19,202012,894470.0,881935.0,False,False,4,0.44719,2020-03-19,0.0,0,3,state,AC,1,0
6,Rio Branco,1200401.0,2020-03-20,202012,413418.0,407319.0,False,False,7,1.69320,2020-03-20,0.0,0,4,city,AC,3,0
7,NaN,12.0,2020-03-20,202012,894470.0,881935.0,False,False,7,0.78259,2020-03-20,0.0,0,4,state,AC,3,0
8,Rio Branco,1200401.0,2020-03-21,202012,413418.0,407319.0,False,False,11,2.66075,2020-03-21,0.0,0,5,city,AC,4,0
9,NaN,12.0,2020-03-21,202012,894470.0,881935.0,False,False,11,1.22978,2020-03-21,0.0,0,5,state,AC,4,0

### Total memory usage: **before optmization**

In [5]:
dataset_total_memory_usage = dataset.memory_usage(deep = True).sum() / (1024 ** 2)

display(
    Markdown(
        f"**Total memory usage:** {dataset_total_memory_usage:.2f} MB"
    )
)

**Total memory usage:** 1553.11 MB

## Memory optimization

### city

#### City names is setted as object, having a lot of unecessary memory used. So lets put "category" type!

In [ ]:
display(
    Markdown(
        f"**data type:** {dataset['city'].dtype}"
    )
)

memory_before = dataset['city'].memory_usage(deep = True) / (1024 ** 2)

display(Markdown(f"**memory before:** {memory_before:.4f} MB"))

In [ ]:
dataset["city"] = dataset["city"].astype("category")

memory_after = dataset['city'].memory_usage(deep = True) / (1024 ** 2)

display(
    Markdown(
        f"**memory after:** {memory_after:.4f} MB"
    )
)

### city_ibge_code

In [ ]:
display(
    Markdown(
        f"**data type:** {dataset['city_ibge_code'].dtype}"
    )
)

memory_before = dataset["city_ibge_code"].memory_usage(deep = True) / (1024 ** 2)

display(Markdown(f"**memory before:** {memory_before:.4f} MB"))

In [ ]:
dataset["city_ibge_code"] = dataset["city_ibge_code"].round().astype("Int32")


memory_after = dataset["city_ibge_code"].memory_usage(deep = True) / (1024 ** 2)

display(Markdown(f"**memory after:** {memory_after:.4f} MB"))

### date

In [ ]:
display(
    Markdown(
        f"**data type:** {dataset['date'].dtype}"
    )
)

date_memory_before = dataset["date"].memory_usage(deep = True) / (1024 ** 2)

display(
    Markdown(
        f"**Total memory usage:** {date_memory_before:.2f} MB"
    )
)

**Total memory usage:** 246.23 MB

In [7]:
dataset["date"] = pandas.to_datetime(dataset["date"]) 

date_memory_after = dataset["date"].memory_usage(deep = True) / (1024 ** 2)

display(
    Markdown(
        f"**Total memory usage:** {date_memory_after:.2f} MB"
    )
)

**Total memory usage:** 29.40 MB

### last_available_date

In [ ]:
display(
    Markdown(
        f"**data type:** {dataset['last_available_date'].dtype}"
    )
)

last_date_memory_before = dataset["last_available_date"].memory_usage(deep = True) / (1024 ** 2)

display(
    Markdown(
        f"**Total memory usage:** {last_date_memory_before:.2f} MB"
    )
)

**Total memory usage:** 246.23 MB

In [9]:
dataset["last_available_date"] = pandas.to_datetime(dataset["last_available_date"]) 

last_date_memory_after = dataset["last_available_date"].memory_usage(deep = True) / (1024 ** 2)

display(
    Markdown(
        f"**Total memory usage:** {last_date_memory_after:.2f} MB"
    )
)

**Total memory usage:** 29.40 MB

### estimated_population

In [ ]:
display(
    Markdown(
        f"**data type:** {dataset['estimated_population'].dtype}"
    )
)

estimated_population_memory_before = dataset["estimated_population"].memory_usage(deep = True) / (1024 ** 2)

display(
    Markdown(
        f"**Total memory usage:** {estimated_population_memory_before:.2f} MB"
    )
)

**Total memory usage:** 29.40 MB

In [11]:
dataset["estimated_population"] = dataset["estimated_population"].astype("Int32")

estimated_population_memory_after = dataset["estimated_population"].memory_usage(deep = True) / (1024 ** 2)

display(
    Markdown(
        f"**Total memory usage:** {estimated_population_memory_after:.2f} MB"
    )
)

**Total memory usage:** 18.38 MB

### estimated_population_2019

In [ ]:
display(
    Markdown(
        f"**data type:** {dataset['estimated_population_2019'].dtype}"
    )
)

estimated_population_memory_before = dataset["estimated_population_2019"].memory_usage(deep = True) / (1024 ** 2)

display(
    Markdown(
        f"**Total memory usage:** {estimated_population_memory_before:.2f} MB"
    )
)

**Total memory usage:** 29.40 MB

In [13]:
dataset["estimated_population_2019"] = dataset["estimated_population_2019"].astype("Int32")

estimated_population_memory_after = dataset["estimated_population_2019"].memory_usage(deep = True) / (1024 ** 2)

display(
    Markdown(
        f"**Total memory usage:** {estimated_population_memory_after:.2f} MB"
    )
)

**Total memory usage:** 18.38 MB

### place_type
    - city
    - state
  So... what shall we will do to optimize it? The answer is that:
    make category 'C' for city, and 'S' for state.

In [14]:
place_type_memory_before = dataset["place_type"].memory_usage(deep = True) / (1024 ** 2)

display(
    Markdown(
        f"**Total memory usage:** {place_type_memory_before:.2f} MB"
    )
)

**Total memory usage:** 224.20 MB

In [15]:
dataset['place_type'] = (
    dataset['place_type']
    .replace({"City": 'C', 'State': 'S'})
    .astype("category")
)

place_type_memory_after = dataset["place_type"].memory_usage(deep = True) / (1024 ** 2)

display(
    Markdown(
        f"**Total memory usage:** {place_type_memory_after:.2f} MB"
    )
)

**Total memory usage:** 3.68 MB

### Total memory usage: **after** optimization

In [16]:
dataset_total_memory_usage_after_optimization = dataset.memory_usage(deep = True).sum() / (1024 ** 2)

display(
    Markdown(
        f"**Total memory usage:** {dataset_total_memory_usage_after_optimization:.2f} MB"
    )
)

**Total memory usage:** 876.86 MB

## Missing values

### Amount

In [17]:
display(
    Markdown(f"**Total amount of missing values**: {dataset.isna().sum().sum()}")
)

**Total amount of missing values**: 90223

### Stats

In [18]:
empty_data_reckoning_rendered: DataFrame = DataFrame(dataset.isna().sum().sort_values(ascending = True))
empty_data_reckoning_rendered

                                                   0
last_available_confirmed                           0
state                                              0
place_type                                         0
order_for_place                                    0
last_available_deaths                              0
last_available_death_rate                          0
last_available_date                                0
new_confirmed                                      0
new_deaths                                         0
is_last                                            0
epidemiological_week                               0
date                                               0
is_repeated                                        0
estimated_population_2019                      13646
estimated_population                           13646
city_ibge_code                                 13646
city                                           20119
last_available_confirmed_per_100k_inhabitants  29166

### City values

In [19]:
missing_city_mask: DataFrame = dataset["city"].isna()

empty_city_values: DataFrame = dataset.loc[
    missing_city_mask,
    ["city", "state", "city_ibge_code"]
]

empty_city_values

        city state  city_ibge_code
1        NaN    AC            12.0
3        NaN    AC            12.0
5        NaN    AC            12.0
7        NaN    AC            12.0
9        NaN    AC            12.0
...      ...   ...             ...
3853087  NaN    TO            17.0
3853227  NaN    TO            17.0
3853367  NaN    TO            17.0
3853507  NaN    TO            17.0
3853647  NaN    TO            17.0

[20119 rows x 3 columns]

### city_ibge_code is unnecerary setted as float. Lets convert to int for lesser memory usage.

In [20]:
display(
    Markdown(
        f"**data type:** {dataset['city_ibge_code'].dtype}"
    )
)

memory_before = dataset["city_ibge_code"].memory_usage(deep = True) / (1024 ** 2)

display(Markdown(f"**memory before:** {memory_before:.4f} MB"))

**data type:** float64

**memory before:** 29.4011 MB

In [21]:
# dataset.loc[dataset["city_ibge_code"].isna(), "city_ibge_code"] = 0

dataset["city_ibge_code"] = dataset["city_ibge_code"].round().astype("Int32")


memory_after = dataset["city_ibge_code"].memory_usage(deep = True) / (1024 ** 2)

display(Markdown(f"**memory after:** {memory_after:.4f} MB"))

**memory after:** 18.3758 MB

### City names is setted as object, having a lot of unecessary memory used. So lets put "category" type!

In [22]:
display(
    Markdown(
        f"**data type:** {dataset['city'].dtype}"
    )
)

memory_before = dataset['city'].memory_usage(deep = True) / (1024 ** 2)

display(Markdown(f"**memory before:** {memory_before:.4f} MB"))

**data type:** object

**memory before:** 288.8445 MB

**memory after:** 7.8761 MB